### ISSUE TITLE
Különböző árképzések vizsgálata és dokumentálása

### ISSUE THREAD

**Issue by szabolcsmaj** [szabolcsmaj/uzemprogram#1]
# A cél: 
Készíteni egy rövid de lényegre törő leírást arról, hogy miként kalkulálja a program a különböző árképzéseknél egy termék árát. 

Az elvárt formátum:

1. Árképzése neve
2. Tesztelt termék és annak mozgásai (ez lehet mindegyiknél ugyanaz)
3. Elvárt ár a terméknél (ha van ilyen)
4. Megfigyelt ár a terméknél
5. Szóbeli ismertetője a kalkuláció logikájának
6. Rövid technikai ismertetője az algoritmusnak (milyen táblába nyúl bele, egyéb fontos momentumok, stb)

# Ismertetés

A következő árképzéseket használja az alkalmazás:
 - Átlagár
 - Utolsó ár
 - FIFO ár

Meg kell vizsgálni, hogy egy példatermékkel milyen értékeket hoz a fenti árképzések használatával a program. A terméknek lehetőleg csak 1-2 mozgása legyen az áttekinthetőség és ellenőrizhetőség miatt.

Az árképzési opciókat el lehet érni:
 - Készlet formról
 - Leltár formról
 - Bizonylat formról

@ravencs szerint mindegyik formon más és más számításokat hajt végre a program. 

Utolsó lépésként meg kell vizsgálni, hogy miért használnak más számítást formonként. Lehet, hogy csak elsőre tűnik másnak, valójában csak egy kis extra információval ruházzák fel az algoritmust. Másik esetben előfordulhat, hogy a készlet formon csak meghívnak egy tárolt eljárást, míg a leltár formon egy komplikált SQL lekérdezést hívnak le. Ez utóbbit lehet, hogy az előbb említett tárolt eljárás már tartalmazza magában, csak a tárolt eljárást utólag adták hozzá és lusták voltak az SQL lekérdezést átformálni a tárolt eljárás hívásra és úgy hagyták.

EDIT:

Árkalkulációnak utánakérdeztem, a FIFO és az átlagár közötti különbségek a következőképpen alakulnak:

Tegyük fel, hogy van egy 100 db-os nyitó készletem X termékből ami 100 Ft-ért lett bevételezve. Ezen felül bevettem még 20 db-ot 150 Ft-ért.

| Típus | Mennyiség | Beszerzési Ár |
| --- | --- | --- | 
| Nyitó | 100 | 100 Ft |
| Bevételezés | 20 | 150 Ft |

Ha ekkor nézünk egy FIFO árat vagy egy átlagárat akkor ugyanazt fogja adni mind a kettő. Ennek az oka a következő:
 - Az átlagár az **összes** _beérkező_ (nyitó készlet, bevételezés, stb) tranzakció általi árak súlyozott átlagárát veszi. Esetünkben ez (100 * 100 + 20 * 150) / (100 + 20) = **108,3 Ft**
 - A FIFO a _beérkező_ tranzakció alapján számol súlyozott átlagot de csak azokat veszi, amelyek még a készleten vannak. Ezen számolás eredménye meg fog egyezni a súlyozott átlagár eredményével (**108,3 Ft**) mivel a készletről semmi nem került levonásra.

A készletünket "megbolygatjuk" és eladunk 70 db X-et.

| Típus | Mennyiség | Beszerzési Ár |
| --- | --- | --- | 
| Nyitó | 100 | 100 Ft |
| Bevételezés | 20 | 150 Ft |
| Eladás | 70 | - |

A számolások a következőképpen fognak alakulni:
 - Az átlagár ugyanannyit fog adni mint az előző mivel csak az _összes_ beérkező tranzakciót veszi alapul. Jelen esetben ez ugyanúgy (100 * 100 + 20 * 150) / (100+20) = **108,3 Ft**
 - A FIFO viszont változni fog mert ez csak azokat veszi figyelembe amik még a készleten vannak. A készleten jelen pillanatban 120 - 70 = 50 db van X-ből. A nevéből adódóan (first in, first out) a régi termékek kerülnek "kisöprésre", ezért a következő lépések történnek:
    - A legutolsó 20 bevételezést veszem először alapul: 20 db 150 Ft-os bevétel történt. Maradt még 50 - 20 = 30 db amit még "le kell fednem"
    - A következő bevételezési tranzakció időben visszafelé haladva a 100 db-os nyitó készleté. A készletről elszámolandó mennyiség már csak 30 db ezért 30 db 100 Ft-os tranzakciót fogok még venni a számolás alapjául
    - A számolás tehát így alakul: (20 * 150 + 30 * 100) / (20 + 30) = **120 Ft**

**Comment by ravencs** [comment]
Halo

**Comment by ravencs** [comment]
# Tesztelés menete
## Teszt 001
### Újonnan létrehozott cikk, ugyanaz (lehet semmi is) a gyártási szám, ugyanaz a raktár
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Bevételezés "X"-ből az 1-es raktárba "B" beszerzési árért aminek a nyitókészleti beszerzési ára "A" volt (nem 0)
3. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
4. Bevételezés "X"-ből az 1-es raktárba "C" beszerzési árért
5. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből mínuszba megy
6. Bevételezés "X"-ből az 1-es raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet az ABC raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 100 | 100 | 100 | 100 |

2. 50 db bevételezése 200 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 150 | 200 | 133,33 | 133,33 |

3. 75 db eladása az ABC raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 75 | 200 | 133,33 | 166,67 |

4. 50 db bevételezése 150 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 125 | 150 | 140 | 160 |

5. 150 db eladása az ABC raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | -25 | 150 | 0 | 0 |

6. 50 db bevételezése 125 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 25 | 125 | 122,73 | 125 |

## Teszt 002
### Újonnan létrehozott cikk, ugyanaz (lehet semmi is) a gyártási szám, különböző raktárak
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Bevételezés "X"-ből a 2-es raktárba "B" beszerzési árért aminek a nyitókészleti beszerzési ára "A" volt (nem 0)
3. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
4. Bevételezés "X"-ből az 1-es raktárba "C" beszerzési árért
5. "X" eladása a 2-es raktárból úgy, hogy a készlet "X"-ből mínuszba megy
6. Bevételezés "X"-ből a 2-es raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet a VETCO raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 100 | 100 | 100 | 100 |

2. 50 db bevételezése 200 Ft-ért a Főraktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 100 | 200 | 100 | 100 |
| Főraktár | 50 | 200 | 200 | 200 |
| Összesített | 150 | 200 | 133,33 | 133,33 |

3. 50 db eladása a VETCO raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 50 | 200 | 66,67 | 100 |
| Főraktár | 50 | 200 | 200 | 200 |
| Összesített | 100 | 200 | 133,33 | 150 |

4. 50 db bevételezése 150 Ft-ért a VETCO raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 100 | 150 | 108,33 | 125 |
| Főraktár | 50 | 150 | 200 | 200 |
| Összesített | 150 | 150 | 138,89 | 150 |

5. 75 db eladása a Főraktárból

- Volt figyelmeztetés, hogy a készlet mínuszba fog menni

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 100 | 150 | 108,33 | 125 |
| Főraktár | -25 | 150 | 0 | 0 |
| Összesített | 75 | 150 | 77,78 | 166,67 |

6. 25 db bevételezése 125 Ft-ért a Főraktárba

- Főraktárat kiválasztva és a "Csak a készlettel rendelkező áruk mutatása" jelölőnégyzetet ki vagy bekapcsolva sem mutatja az alapanyagot

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| VETCO | 100 | 125 | 108,33 | 125 |
| Főraktár | x | x | x | x |
| Összesített | 100 | 125 | 108,33 | 156,25 |

## Teszt 003
### Adatbázisban már létező cikk, ugyanaz (lehet semmi is) a gyártási szám, ugyanaz a raktár
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Bevételezés "X"-ből az 1-es raktárba "A" beszerzési árért aminek a nyitókészleti beszerzési ára 0 volt
3. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
4. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből mínuszba megy
5. Bevételezés "X"-ből az 1-es raktárba "B" beszerzési árért
### Példa:
1. Nyitókészlet a BAYER raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 0 | 0 | 0 |

2. 10 db bevételezése 100 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 15 | 100 | 66,67 | 66,67 |

3. 7 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 8 | 100 | 66,67 | 100 |

4. 10 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | -2 | 100 | 0 | 0 |

6. 12 db bevételezése 150 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 10 | 150 | 138,10 | 150 |

## Teszt 004
### Adatbázisban már létező cikk, ugyanaz (lehet semmi is) a gyártási szám, ugyanaz a raktár, csaló form használatával módosított beszerzési ár
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Csaló form használata, amivel "X" új beszerzési árat kap ("A")
3. Bevételezés "X"-ből az 1-es raktárba "B" beszerzési árért
4. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
5. Bevételezés "X"-ből az 1-es raktárba "C" beszerzési árért
6. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből mínuszba megy
7. Bevételezés "X"-ből az 1-es raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet a BAYER raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 0 | 0 | 0 |

2. Csaló form használata, amitől az új beszerzési ár 100 Ft lesz

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 0 | 100 | 0 |

3. 10 db bevételezése 150 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 15 | 150 | 133,33 | 100 |

4. 7 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 8 | 150 | 133,33 | 150 |

5. 10 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | -2 | 150 | 0 | 0 |

6. 12 db bevételezése 200 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 10 | 200 | 190,48 | 200 |

## Teszt 005
### Adatbázisban már létező cikk, ugyanaz (lehet semmi is) a gyártási szám, ugyanaz a raktár, csaló form használatával módosított beszerzési ár és készlet
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Csaló form használata, amivel "X" új beszerzési árat kap ("A") és új mennyiséget
3. Bevételezés "X"-ből az 1-es raktárba "B" beszerzési árért
4. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
5. Bevételezés "X"-ből az 1-es raktárba "C" beszerzési árért
6. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből mínuszba megy
7. Bevételezés "X"-ből az 1-es raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet a BAYER raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 0 | 0 | 0 |

2. Csaló form használata, amitől az új beszerzési ár 100 Ft, az új készlet 50 db lesz

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 50 | 0 | 100 | 0 |

3. 10 db bevételezése 150 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 60 | 150 | 108,33 | 100 |

4. 50 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 10 | 150 | 108,33 | 150 |

5. 15 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | -5 | 150 | 0 | 0 |

6. 10 db bevételezése 200 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 200 | 169,44 | 200 |

## Teszt 006
### Adatbázisban már létező cikk, ugyanaz (lehet semmi is) a gyártási szám, olyan raktárból történő eladás ahol nem volt készleten az adott cikk, csaló form használatával módosított beszerzési ár és készlet
1. Nyitókészlet "X" alapanyagból az 1-es raktárban
2. Csaló form használata, amivel "X" új beszerzési árat kap ("A") és új mennyiséget
3. Bevételezés "X"-ből az 1-es raktárba "B" beszerzési árért
4. "X" eladása az 1-es raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
5. "X" eladása a 2-es raktárból úgy, hogy "X" abban a raktárban nem volt készleten
6. Bevételezés "X"-ből az 1-es raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet a BAYER raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 5 | 0 | 0 | 0 |

2. Csaló form használata, amitől az új beszerzési ár 100 Ft, az új készlet 50 db lesz

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 50 | 0 | 100 | 0 |

3. 10 db bevételezése 150 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 60 | 150 | 108,33 | 100 |

4. 50 db eladása a BAYER raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 10 | 150 | 108,33 | 150 |

5. 15 db eladása a Főraktárból úgy, hogy itt nem is volt készleten

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 10 | 150 | 108,33 | 150 |
| Főraktár | -15 | 150 | 0 | 0 |
| Összesített | -5 | 150 | 0 | 0 |

6. 10 db bevételezése 200 Ft-ért a BAYER raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| BAYER | 20 | 200 | 154,17 | 175 |
| Főraktár | -15 | 200 | 0 | 0 |
| Összesített | 5 | 200 | 45,17 | 200 |

**Comment by szabolcsmaj** [comment]
Írtam Szabó Gábornak egy levelet amit te is megkaptál mert CC-ztelek. Ők fejlesztették anno a DBS-t meg az üzemet is.
Mindenképpen meg kéne várni, hogy mit válaszol a levélben feltett kérdésekre. Ettől függetlenül ide is bemásolom az oda bevágott linket: http://merlegkepestanoncok.hu/szamvitel/keszletertekeles-atlagar-modszerrel

A csaló formnál biztosan kelleni fog egy olyan feltétel, hogy ha az adott tételből nincs más bevételezés, csak a nyitó készlet, akkor az utolsó árat is írja át a megadott árra. Ehhez használhatod az *EXISTS* SQL parancsot:

    IF( EXISTS ( 
        SELECT B.ID_BIZONYLAT
        FROM BIZONYLAT B JOIN
                    BIZONYLATTETEL BT ON BT.ID_BIZONYLAT = B.ID_BIZONYLAT
        WHERE BT.ID_CIKK = :P_ID_CIKK AND
                      B.EV = :P_YEAR AND
                      B.TYPE != 'NYITO_BIZONYLAT' AND
                      B.IRANY = 1 --vagy ami a bejövő bizonylatot jelöli 
       )) THEN UPDATE_UTOLSO_AR();

Lehet még szűkíteni kell más feltétel szerint is, pl.: a bizonylat típusa csak 1-2 bizonyos fajta lehet azon túl, hogy "nem nyitó"

**Comment by ravencs** [comment]
## Teszt 007
### Adatbázisban már létező cikk, ugyanaz a gyártási szám (lehet semmi is), olyan raktárból történő eladás ahol volt készleten az adott cikk, csaló form használatával módosított beszerzési ár és készlet, eladás nagy árréssel, készlet 0-ra csökkentése majd újbóli feltöltése

1. Nyitókészlet "X" alapanyagból az ABC raktárban
2. Csaló form használata, amivel "X" új beszerzési árat kap ("B") és új mennyiséget
3. Bevételezés "X"-ből az ABC raktárba "C" beszerzési árért
4. "X" eladása nagy árréssel az ABC raktárból úgy, hogy a készlet "X"-ből nem megy mínuszba
5. Bevételezés "X"-ből az ABC raktárba "C" beszerzési árért
6. "X" eladása nagy árréssel (nagyobb mint a 4. pontban) az ABC raktárból úgy, hogy a készlet "X"-ből 0 lesz
7. Bevételezés "X"-ből az ABC raktárba "D" beszerzési árért
### Példa:
1. Nyitókészlet az ABC raktárban

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 28 | 0 | 0 | 0 |

2. Csaló form használata, amitől az új beszerzési ár 100 Ft, az új készlet 50 db lesz

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 50 | 0 | 100 | 0 |

3. 50 db bevételezése 150 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 100 | 150 | 125 | 96,15 |

4. 75 db eladása 500 Ft-ért az ABC raktárból

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 25 | 500 | 285,71 | 150 |

5. 25 db bevételezése 150 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 50 | 150 | 217,86 | 150 |

6. 50 db eladása 650 Ft-ért az ABC raktárból

- Csak összesített készletben jelenik meg és csak akkor ha ki van kapcsolva, hogy csak azokat a termékeket mutassa amiből van készleten

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 0 | 650 | 0 | 0 |

7. 100 db bevételezése 200 Ft-ért az ABC raktárba

| Raktár | Mennyiség (db) | Utolsó (Ft) | Átlag (Ft) | FIFO (Ft) |
| --- | --- | --- | --- | --- |
| ABC | 100 | 200 | 200 | 200 |
