### ISSUE TITLE
Cheat form a nyitó készleten túl az eladások beszerzési árát is számolja újra

### ISSUE THREAD

**Issue by szabolcsmaj** [szabolcsmaj/uzemprogram#4]
## Általános ismertetés:

Mindenek előtt tisztázni kell, hogy a beszerzési ár kalkulálás azért kell, hogy ki tudjuk számolni egy adott terméken levő profitot. Ha eladok egy kólát 100 Ft-ért akkor tudnom kell, hogy az nekem mennyibe fájt. Ha minden eladáshoz tartozik egy *kalkulált* bekerülési érték akkor ez a számítás egy egyszerű kivonással történik: `eladási ár - beszerzési ár`

3 különböző "mozgást" veszünk alapul a készletek árkalkulációjakor:
 - Nyitókészlet: A zárás után az áthozott cikkek mennyisége és kalkulált beszerzési ára. Az árnak FIFO árnak kell lennie
 - Beszerzések: pl szállítólevélen felrögzítik a rendszerbe a mennyiséget és a beszerzési árát a számlán szereplő árral adják meg
 - Kimenő forgalmak: pl kimenő szállítólevél. Ennek készítésekor a userek *nem* foglalkoznak a beszerzési árral hanem azt a program kikalkulálja szintén FIFO szerint (utánanézni, hogy valóban FIFO szerint van-e)

## Feladat:

A cheat formmal ha módosítunk egy termék beszerzési árán akkor 2 dolgot kellene csinálnia:

 1. A nyitókészlet bizonylathoz tartozó BIZONYLATTETEL bejegyzés beszerzési árát módosítani a megadott árra
 2. Az összes nyitás óta történt kimenő forgalomnál az adott cikkre kalkulált beszerzési árat újra kell számolnia

## Példa:

A múlt év kolosszálisan szarul lett kezelve és évzárás után a nyitó készleten az X termék 0 Ft-os beszerzési áron lett rögzítve.

| Típus | Mennyiség | Beszerzési Ár (FIFO) | Eladási ár | Profit |
| --- | --- | --- | --- | --- |
| Nyitó | 100 | 0 Ft | - | - |
| Eladás | 70 | 0 | 200 Ft | **200 Ft** |
| Bevételezés | 50 | 150 Ft | - | - |
| Új eladás | 40 | (30x0 + 10x150) / 40 => 37,5 | 200 Ft | **162,5 Ft** |

A könyvelésen utánaszámolnak és kiderül, hogy a nyitó a valóságban 120 Ft volt. A cheat formon ha *NEM* frissítjük az eladásokat akkor ugyanúgy nem tudnak majd utólag profitot számolni *a régi eladásokra*.

| Típus | Mennyiség | Beszerzési Ár (FIFO) | Eladási ár | Profit |
| --- | --- | --- | --- | --- |
| Nyitó | 100 | (Frissítve) 120 Ft | - | - |
| Eladás | 70 | 0 | 200 Ft | **200 Ft** |
| Bevételezés | 50 | 150 Ft | - | - |
| Új eladás | 40 | (30x120 + 10x150) / 40 => 127,5 | 200 Ft | **72,5 Ft** |

Ha a cheat form a régi eladásokat is frissítené akkor az utólagos számolásoknál már helyesen a következő adatokat hozná:

| Típus | Mennyiség | Beszerzési Ár (FIFO) | Eladási ár | Profit |
| --- | --- | --- | --- | --- |
| Nyitó | 100 | (Frissítve) 120 Ft | - | - |
| Eladás | 70 | 120 Ft | 200 Ft | **80 Ft** |
| Bevételezés | 50 | 150 Ft | - | - |
| Új eladás | 40 | (30x120 + 10x150) / 40 => 127,5 | 200 Ft | **72,5 Ft** |

**Comment by ravencs** [comment]
Az nyitókészlet módosítása után a számolás bevételezési számla esetében abból áll, hogy az egységára lesz a beszerzési ára, kiadások esetében pedig az összes számla alapján számolódik. Példa:

| ID | Type | Quantity (db) | Amount (Ft) | FIFO                                                                                                      |   |             |
|----|------|---------------|-------------|-----------------------------------------------------------------------------------------------------------|---|-------------|
| 1  | NYI  | 100           | 100         |                                                                                            | = | 100         |
| 2  | BEV  | 10            | 110         |                                                                            | = | 110 |
| 3  | BEV  | 20            | 120         |                                                             | = | 120 |
| 4  | BEV  | 30            | 130         |                                               | = | 130      |
| 5  | ANY  | -60           | 200         | (60 * 100) / 60                                 | = | 100         |
| 6  | ANY  | -60           | 300         | (40 * 100 + 10 * 110 + 10 * 120) / 60 | = | 105       |
