### ISSUE TITLE
Bizonylatkészítés - Bizonylattétel adatlap táblázatból eltűnő adatok

### ISSUE THREAD

**Issue by ravencs** [szabolcsmaj/uzemprogram#5]
Bizonylatkészítés formon egy új tétel hozzáadásakor a készletinformáció táblázat egy cellájába való kattintást követően egy szövegdoboz vezérlőre történő kattintáskor eltűnik a táblázatból a korábban kijelölt cella értéke aminek nem szabadna megtörténnie. 
Valószínűleg teljes sor kijelölésére való átállás után a bug megszűnne, mivel jelenleg nincs értelme kijelölni a cellákat.

**Comment by szabolcsmaj** [comment]
Ha ez megoldja a problémát akkor go 4 it!

**Comment by ravencs** [comment]
Nem ez oldotta meg, de ezt is bekapcsoltam.
