### ISSUE TITLE
Bizonylatkészítés - Bizonylattétel adatlap gyártási számának másolása

### ISSUE THREAD

**Issue by ravencs** [szabolcsmaj/uzemprogram#6]
Gyártási szám jelenleg kis-nagybetű érzékeny, ez létrehozhat duplikációkat egy adott tételből feleslegesen, illetve a gyártási szám néha bonyolultabb formátumú és nagyon figyelni kell beíráskor.

Lehetséges megoldás lehet a készletinformáció táblázatra kétszer kattintva a gyártási szám másolása, vagy context menü másolási lehetősége.

#5

**Comment by ravencs** [comment]
Ha a user kétszer kattint a készletinfó táblázatra akkor az adott sor gyártási száma vágólapra kerül, ha kétszer kattint a gyártási szám szövegdobozba akkor beszúrja a vágólap tartalmát amit max 50 karakterre állítottam a biztonság kedvéért (valószínűleg elég nagy overkill).

**Comment by szabolcsmaj** [comment]
Ez most pontosan hol van? Mikor jön elő mint probléma?
