### ISSUE TITLE
Munkalapot újra kéne tervezni

### ISSUE THREAD

**Issue by szabolcsmaj** [szabolcsmaj/uzemprogram#8]
## Munkalap aktuális állapota:

Jelenleg a munkalap működése buta:
 1. Több terméket is hozzá lehet adni a tételeihez, holott 1 munkalap = 1 késztermék készítése
 1. A hozzáadott alapanyagoknál szintén több cikket is felvehetünk, holott 1 termék 1 alapanyagból áll (ne felejtsük el, hogy ez KISZERELŐ üzem. Nem végeznek gyártást, csak átcsomagolnak egy nagy zacskó valamit kis flakonokba)
 1. Késztermék bevételezésnél szintén csak "javasol" a munkalap egy terméket, ide is felvihetünk bármit

## Javaslat:

Kéne egy új munkalap formot készíteni:
 1. Nagy betűkkel látszana az az 1 db késztermék amit az adott munkával elő kívánnak állítani.
 1. Külön résznél lenne kiemelve a kiosztott alapanyag mennyisége. Itt is csak 1 alapanyagot lehetne felvenni
 1. Egy gridben mutatná a felvitt göngyölegeket a termék
 1. A késztermékek bevételezésének is lenne egy külön grid mennyiséggel és dátummal
 1. Készterméket csak akkor vételezhetnének be ha már van alapanyag és göngyöleg ráosztva az adott munkalapra
 1. Az alapanyagok + göngyölegek bevételezési árát összeadná a program majd leosztaná a munkalap késztermék mennyiségével. Ezzel kiszámolná a beszerzési árát az adott készterméknek.
 1. Késztermék bevételezésekor az előző pontban felvázoltak alapján számolná ki a program a késztermék bekerülési árát
 1. Fontos, hogy ha már volt késztermék bevételezés, de a munkalapon módosul az alapanyag vagy a göngyöleg mennyisége (többet raknak rá, visszavesznek) akkor vagy azonnal, vagy a munkalap lezárásakor frissíteni kell az addig bevett késztermékek beszerzési árát
 1. Erika még említette, hogy bizonyos termékeknél van valami környezetvédelmi adó vagy akár egyéb csomagolási költség (pl gép üzemeltetése). A munkalapon ezt is le lehetne kezelni (pl egységenként 12 Ft a gép költsége) és ezt hozzáadná a végén a bekerülési értékhez. Még tisztázni kell, hogy pontosan mik az igények.

Ez a módosítás természetesen eredményezhet egy súlyosabb adatbázis struktúra változást is. Ezen felül valószínűleg a több másik formnak is kéne egy új köntös.

A végső állapotban valószínűleg a szállítóhoz és a számlához hasonlóan a mozgásnemek beállításánál minden egyes új formhoz lesz egy új radiobutton.

**Comment by ravencs** [comment]
Átvittem GitLab-ra.
