### ISSUE TITLE
Adatszinkronizáció implementálása

### ISSUE THREAD

**Issue by ravencs** [szabolcsmaj/uzemprogram#9]
## Cél:
DBS-sel megegyező működésű szinkronizáció megvalósítása, egyelőre csak pár fontosabb táblán. Bizonylat, bizonylattétel és napló.

## Feladatok:
 - [ ] Szinkronprogram
 - [ ] Fontosabb táblák SYNC ID-kkel való kiegészítése
 - [ ] Triggerek implementálása
 - [ ] SYNC, TELEPHELYSYNC és DELETESYNC táblák implementálása az üzem adatbázisba
 - [ ] Tesztkörnyezet létrehozása
 - [ ] Működés tesztelése

**Comment by szabolcsmaj** [comment]
Nincs szükség rá mert direktben fognak csatlakozni az adatbázisra
